### ISSUE TITLE
Team12 Review: [Hazard Analysis] File Manager

### ISSUE THREAD

**Issue by YoussefRizkalla** [agentvv/MTOBridge#13]
Writing to files seems to be a critical aspect of the system - some hazards cite saving to a file as a recommended action. What if the file manager runs out of disk space or memory? No method is described to mitigate such a case. A potential way to mitigate that would be to describe some sort of buffering mechanism.

CC: @CSchank

**Comment by agentvv** [comment]
As the file manager is being implemented by the OS, its hazards are out of scope.
