### ISSUE TITLE
Team 12 Review: [Hazard Analysis] Handling floating point rounding and inaccuracy errors

### ISSUE THREAD

**Issue by Tamas-Leung** [agentvv/MTOBridge#15]
When doing calculations, floating point rounding issues and inaccuracies can amass leading to potential large unexpected errors. What is the acceptable range of error tolerance? What will be the recommended actions when the error is too large? 

@CSchank

**Comment by agentvv** [comment]
This hazard has to do with the implementation of the MATLAB module, so it is out of scope.
