### ISSUE TITLE
Team 12 Review: [Hazard Analysis] Input handler failure prevented by validating inputs again [HD-2]

### ISSUE THREAD

**Issue by AntonKanug** [agentvv/MTOBridge#16]
References hazard HD-2 

Input handler failing to handle an incorrect type of input is to be prevented by validating the input before passing it on. However, failure occurs on the engine side and the input handler's main purpose is to validate the input. Due to this the recommended action is a circular action (validating inputs again) and should be addressed in another way.

@cschank

**Comment by agentvv** [comment]
Appropriate modifications to HD-2 have been made.
