### ISSUE TITLE
Team 12 Review: [Hazard Analysis] Input handler hazards

### ISSUE THREAD

**Issue by Tamas-Leung** [agentvv/MTOBridge#18]
The Input handler hazards are not hazards, as those are functional requirements for the input handler. The input handlers functionality is to ensure the input is correct for MATLAB usage, therefore HD-1, HD-2 and HD-3 are not hazards.

**Comment by agentvv** [comment]
The input handler's functional requirements relate to taking in user data, the identified hazards are indeed hazards.
