### ISSUE TITLE
Team 11 Review: [VnV Plan] Team Member Roles

### ISSUE THREAD

**Issue by mehtaj8** [agentvv/MTOBridge#19]
@tingyuw

Specific team member roles need to be included in the plan. Rather than making everyone responsible for verification and validation as a whole, the tasks can be split up in the plan per person so when the time comes, everyone is aware of their responsibilities

**Comment by Adham-Badawy** [comment]
Thanks for the feedback, we got similar feedback for the TA on specific assignments as well, and while we do believe that overall team roles should still be general, specific members have no been assigned to specific reviews in rev1
