### ISSUE TITLE
Team 11 Review: [VnV Plan] Functional Tests, Test Case Derivation Missing details

### ISSUE THREAD

**Issue by BilalShakh** [agentvv/MTOBridge#20]
An explanation regarding the relation of the Test case creation and output to its related FR in SRS could greatly help in validating your Traceability Matrix. And specifically could help in improving the Traceability of Requirements in the rubric as it states "traceability between requirements and test cases is clearly documented.".

**Comment by Adham-Badawy** [comment]
Thanks for the feedback, in the Rev1 version of the document we believe that the test case derivation section fulfills this need
