### ISSUE TITLE
Team 11 Review: [VnV Plan] Including Abbreviations in Section 2

### ISSUE THREAD

**Issue by sharjilm** [agentvv/MTOBridge#21]
Section 2 refers to section 1.4 of the SRS. However, upon looking there, there seems to be a lack of different abbreviations that are used throughout this document and what they mean exactly. Instead of defining the abbreviation in the body of the document when it's first used, it would be easier if the abbreviation is just mentioned at the top in section 2 along with a description of what it means.

@tingyuw

**Comment by Adham-Badawy** [comment]
Thanks for the feedback, we've decided not to implement this as we did not find it relevant for the Rev1 version of the document outside of the terms MG and MIS which are expected to be common knowledge for the audience
