### ISSUE TITLE
Team 10 Review: Missing Component Diagram

### ISSUE THREAD

**Issue by michaela-schnull** [agentvv/MTOBridge#22]
A component diagram can still be created for a software project, even if there are not physical components. i.e. the analysis tool, bridge tool, report tool could be different components of your application.

**Comment by yazdinip** [comment]
Thank you so much for the comment, completely agree that even a Software program can have a physical component diagram nevertheless our scenario is a bit different. Our solution will not be working or interacting with any other sort of Software in its current implementation and as such, we didn't really see the need. Thanks again
