### ISSUE TITLE
Team 10 Review: [DesDoc] MG Module Hierarchy

### ISSUE THREAD

**Issue by michaela-schnull** [agentvv/MTOBridge#24]
All the modules currently under hardware hiding should be behaviour hiding modules. Data storage is a required behaviour of MTOBridge. The hardware-hiding module is implemented by the OS.

**Comment by yazdinip** [comment]
Thanks for the comment but hardware-hiding modules are responsible for managing the resources and interfaces with hardware components. Their primary purpose is to encapsulate the details of how the hardware operates and provide an abstract interface to the rest of the system. In the case of data storage, a hardware-hiding module would manage reading from and writing to storage devices while shielding the rest of the software from the complexities and specifics of the hardware.
