### ISSUE TITLE
Team 10 Review: [DesDoc] MG Data Format Hiding Modules

### ISSUE THREAD

**Issue by michaela-schnull** [agentvv/MTOBridge#25]
Be more specific about the secrets/services of the data format hiding modules than "how to manage all user input data regarding <configuration>" - is the secret the format and structure of the input data? Does the module verify input data? (input data verification is mentioned in the system design doc, so I assume these modules verify the input data)

**Comment by yazdinip** [comment]
Thank you so much for the input. Clarified some of the secrets for better understanding nevertheless in that case, the intention is really about managing the Hardware-hiding modules that include saving and loading in a way such that information hiding is practiced.
