### ISSUE TITLE
Team 10 Review: [DesDoc] MG Save to File System Modules

### ISSUE THREAD

**Issue by michaela-schnull** [agentvv/MTOBridge#26]
The secrets of the 'save to file system' modules are structured as "how to visualize <some type of data>". Is the secret 'visualizing' the data, or is it more specifically the format/structure of the output file?

**Comment by yazdinip** [comment]
Apologies for the confusion, made a few changes to clarify the wording. We have divided the saving modules such that the visualization of the saver is separate from the actual saving process with the correct format. The secret in that scenario is the saving process with the correct format..
