### ISSUE TITLE
Team31 Review: 2.4 Functional Requirements/Phase In Plan: FR1 could be given more context

### ISSUE THREAD

**Issue by atunney** [agentvv/MTOBridge#3]
I think the functional requirement 

FR.1 The Program should be able to call the backend MATLAB functions.

could be elaborated upon more in the rationale or could be a bit more specific as to what backend MATLAB functions are being referred to here, if possible. I was unsure if this was referring to specific functions that already exist in MATLAB, or if it was referring to the prepared MATLAB engines or solvers that were introduced in previous sections of the SRS. As an external reader of the SRS, if I were to try and construct the system starting with this requirement, I think more context would need to be provided as to what 'backend MATLAB functions' means here.

@tomashetMcMaster

**Comment by jandricd** [comment]
Agreed, updating to be more clear.
